### ISSUE TITLE
studio help link is 404

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#115]
When logged in at http://studio-mavoix.opencraft.hosting the **Help** link (top right) leads to http://edx.readthedocs.io/projects/open-edx-ca/en/named-release/dogwood.rc/index.html which is 404

**Comment by antoviaque** [comment]
@dachary Thanks! Looks like an issue with Read the Docs, the official links from http://docs.edx.org/ are down too. 

@catong Are you aware of this? If not do you want us to create a DOC ticket for this issue?

**Comment by catong** [comment]
@antoviaque Thanks for bringing this to our attention. Is that Studio page specific to a Dogwood-based instance?
I think we updated the "Building and Running" guide and the path changed. The correct link should now be:
http://edx.readthedocs.io/projects/open-edx-ca/en/named-release-dogwood.rc/getting_started/get_started.html
I'll investigate our process for fixes to past named releases.

**Comment by antoviaque** [comment]
@catong Yes, I think this is specific to dogwood - it's likely that the path was changed only in master, after dogwood was released, so that broke the link in the stable version. (You can test an instance running dogwood here: http://studio-dogwood.sandbox.opencraft.com with staff@example.com / edx).

However, that URL seem to be versioned (it contains "dogwood.rc"), so I'm not sure why it would have had to change at all, if the corresponding code in dogwood didn't?

I'm not sure what the policy for backports of fixes is now - I think only critical (CAT-1) fixes are backported. In any case, with the upcoming release of Eucalyptus it might not be worth the trouble. But it could be useful to try to prevent in the future - ie when paths change in master, that it doesn't break links the stable version.

**Comment by catong** [comment]
@antoviaque @dachary Thanks for pointing out this issue. We aren't likely to try to fix this either in the Studio page or in ReadtheDocs since Eucalyptus is close to releasing. 

However, we are trying to address the issue by putting a redirect in place to the correct URL, which has a hyphen in place of a forward slash between "named-release" and "dogwood.rc". FYI the correct URL is http://edx.readthedocs.io/projects/open-edx-ca/en/named-release-dogwood.rc/getting_started/get_started.html

**Comment by antoviaque** [comment]
@catong That's great - thank you!

**Comment by antoviaque** [comment]
@dachary This should now be fixed on your instance - the fix, merged upstream, has made it to the latest stable version, which is now available on your instance. If not, let me know.

**Comment by dachary** [comment]
clicking on help [takes me to help](http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-eucalyptus.master/getting_started/get_started.html) which is ... helpful ;-) Thanks !

**Comment by antoviaque** [comment]
:D
