### ISSUE TITLE
wiki is error 500

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#117]
http://mavoix.opencraft.hosting/courses/course-v1:MaVoix+formation.acceleree.0.1+formation.acceleree.0.1/course_wiki fails to load

![edx1](https://cloud.githubusercontent.com/assets/433594/16714280/7a600c22-46be-11e6-90c0-b7c62b9a8097.png)

**Comment by antoviaque** [comment]
@dachary Thanks for reporting this - @bradenmacdonald this would be an interrupt for the sprint fireman (or, since we're Monday, a task for the upcoming sprint with a short deadline).

**Comment by mtyaka** [comment]
Hi @dachary, we looked into this issue and found out that it is caused by the combination of organization name, course number, and course run being too long (longer than 50 characters, `MaVoix+formation.acceleree.0.1+formation.acceleree.0.1` in your case).

We are [working on a fix](https://github.com/edx/django-wiki/pull/22) for the next release of OpenEdX . Porting the fix to dogwood would not be trivial because it includes database migrations that could cause conflicts when upgrading the instance at a later point, so we decided to not backport the fix.

As a workaround I propose you export content from you current course, create a new course with shorter keys, then import your content into the new course.

**Comment by dachary** [comment]
@mtyaka ouch, that's a tough one ! Will do as you suggest, it's an easy workaround :-) Thanks.

**Comment by dachary** [comment]
After export / import at http://mavoix.opencraft.hosting/courses/course-v1:MaVoix+1+2017/course_wiki there still is an error. Could it be that the export still has the long name somewhere despite the URL being shorter ?

**Comment by mtyaka** [comment]
@dachary Ah yes, the wiki slug is stored on the course object and gets exported together with the course, so a simple export-import doesn't fix the problem. I manually changed the wiki slug to `'MaVoix.1.2017'` in the database for you new course so the wiki should now work correctly, but please let us know if you run into any further issues.

**Comment by dachary** [comment]
works ! thanks :-)
