### ISSUE TITLE
Cannot hide old courses

### ISSUE THREAD

**Issue by SlyMaVoix** [open-craft/opencraft#199]
Some of my courses are hidden, and others not.
I don't understand how it works.
I set an end date to the course in the past (from current date) but it doesn't hide the course in my public catalog. I removed all unnecessary dates, in Date and Details View... but nothing works...

see [my instance of opencraft](https://mavoix.opencraft.hosting/) and Edx Demonstration course for example.

I tried this procedure without success : 
[How to Hide a course from the course catalog](http://help.appsembler.com/article/169-how-to-hide-a-course-from-the-course-catalog)

**Comment by antoviaque** [comment]
@bdero @bradenmacdonald Can we have a look at this?

**Comment by bdero** [comment]
I did a little codebase diving to figure this one out; hiding courses has been historically a bit of a weird issue with Open edX. It turns out that in late 2014, Chris Dodge created that advanced setting (Course Visibility in Catalog), but the platform has been [defaulting to the old behavior](https://github.com/edx/edx-platform/pull/5876/files#diff-82bda515879c96ab0641bfcbe58631c3R1857) ever since (which is to essentially ignores the advanced setting).

The way to make it work is to override `COURSE_CATALOG_VISIBILITY_PERMISSION` with the value `see_in_catalog`. However, such a setting override didn't get contributed to edX configuration until [just last month](https://github.com/edx/configuration/pull/3749), so it's not even in Ficus!

@SlyMaVoix I've cherry-picked this small change into the OpenCraft Ficus configuration, added the overrides for your instance, and provisioned/cut over to a new appserver for you, so this setting is [now working](https://mavoix.opencraft.hosting/) and the edX Demonstration Course is now hidden. :)

**Comment by antoviaque** [comment]
@bdero Thanks!

**Comment by SlyMaVoix** [comment]
@bdero Thank you a lot! it works !
